### ISSUE TITLE
[Solana] How to get balances of a Solana token

### ISSUE THREAD

**Issue by EtainLove** [mrtnetwork/On_chain#13]
How to get the balances of a Solana token, I mean not Sol but a custom token.

I tried this and it returns the balance of Sol.

```
      final accountBalance = await _client
          .request(SolanaRPCGetBalance(account: SolAddress(address)));
```

What I want to do is to get balances of token holders. Could you guide me how to do it?

**Comment by mrtnetwork** [comment]
> How to get the balances of a Solana token, I mean not Sol but a custom token.
> 
> I tried this and it returns the balance of Sol.
> 
> ```
>       final accountBalance = await _client
>           .request(SolanaRPCGetBalance(account: SolAddress(address)));
> ```
> 
> What I want to do is to get balances of token holders. Could you guide me how to do it?

hi, you should take a look at rpc methods.
```
  
final r = await r
      .request(SolanaRPCGetTokenAccount(account: account));
  final r = await r
      .request(SolanaRPCGetMintAccount(account: account));

```

**Comment by mrtnetwork** [comment]
I'll close the issue for now. If you have any further questions, feel free to ask!
