### ISSUE TITLE
The bipObj shall not be below account level

### ISSUE THREAD

**Issue by detherminal** [mrtnetwork/On_chain#4]
I am getting this error when I am creating a new mnemonic and try to derive address from it.

Code:

```
mnemonic = Bip39MnemonicGenerator().fromWordsNumber(Bip39WordsNum.wordsNum15).toList().join(" ");
...
final mnemonic = await getMnemonic(); // getMnemonic gets the above mnemonic variable
final seed = CardanoIcarusSeedGenerator(mnemonic).generate();
final cip1852 = Cip1852.fromSeed(seed, Cip1852Coins.cardanoIcarus);
final shelly = CardanoShelley.fromCip1852Object(cip1852);
```

And I am getting the error in `fromCip1852Object(cip1852)`: `The bipObj shall not be below account level`

I do not think I am doing anything wrong as this is literally what the documentation says.

**Comment by mrtnetwork** [comment]
> I am getting this error when I am creating a new mnemonic and try to derive address from it.
> 
> Code:
> 
> ```
> mnemonic = Bip39MnemonicGenerator().fromWordsNumber(Bip39WordsNum.wordsNum15).toList().join(" ");
> ...
> final mnemonic = await getMnemonic(); // getMnemonic gets the above mnemonic variable
> final seed = CardanoIcarusSeedGenerator(mnemonic).generate();
> final cip1852 = Cip1852.fromSeed(seed, Cip1852Coins.cardanoIcarus);
> final shelly = CardanoShelley.fromCip1852Object(cip1852);
> ```
> 
> And I am getting the error in `fromCip1852Object(cip1852)`: `The bipObj shall not be below account level`
> 
> I do not think I am doing anything wrong as this is literally what the documentation says.

you must be in account level if you want to use ```CardanoShelley```

Example:
```
  final mnemonic =
      Bip39MnemonicGenerator().fromWordsNumber(Bip39WordsNum.wordsNum12);
  final seed = CardanoIcarusSeedGenerator(mnemonic.toStr()).generate();
  final cip1852 = Cip1852.fromSeed(seed, Cip1852Coins.cardanoIcarus);

  /// m/1852'/1815'/0'
  final deriveToAccount = cip1852.purpose.coin.account(0);
  final shelly = CardanoShelley.fromCip1852Object(deriveToAccount);
  print(shelly.privateKeys.privAddrKey.toHex());
  print(shelly.privateKeys.privSkKey.toHex());

```

**Comment by detherminal** [comment]
That worked, thanks so much. One last question: I don't get the same result as the Yoroi wallet, is there a way to make it so?
My code for total derivation:
```
final mnemonic = await getMnemonic();
final seed = CardanoIcarusSeedGenerator(mnemonic).generate();
final cip1852 = Cip1852.fromSeed(seed, Cip1852Coins.cardanoIcarus);
final derivationAccount = cip1852.purpose.coin.account(0);
final shelly = CardanoShelley.fromCip1852Object(derivationAccount);
final paymentPublicKey = shelly.bip44.publicKey.compressed;
final stakePublicKey = shelly.bip44Sk.publicKey.compressed;
final address = ADABaseAddress.fromPublicKey(basePubkeyBytes: paymentPublicKey, stakePubkeyBytes: stakePublicKey).address;
```

**Comment by mrtnetwork** [comment]
> That worked, thanks so much. One last question: I don't get the same result as the Yoroi wallet, is there a way to make it so? My code for total derivation:
> 
> ```dart
> final mnemonic = await getMnemonic();
> final seed = CardanoIcarusSeedGenerator(mnemonic).generate();
> final cip1852 = Cip1852.fromSeed(seed, Cip1852Coins.cardanoIcarus);
> final derivationAccount = cip1852.purpose.coin.account(0);
> final shelly = CardanoShelley.fromCip1852Object(derivationAccount);
> final paymentPublicKey = shelly.bip44.publicKey.compressed;
> final stakePublicKey = shelly.bip44Sk.publicKey.compressed;
> final address = ADABaseAddress.fromPublicKey(basePubkeyBytes: paymentPublicKey, stakePubkeyBytes: stakePublicKey).address;
> ```

you should derive to address index to get the same result 

```dart
  final mnemonic = Mnemonic.fromString(
      "speed certain today drill enrich plunge champion focus silver banner physical panic nerve address bulk");
  final seed = CardanoIcarusSeedGenerator(mnemonic.toStr()).generate();
  final cip1852 = Cip1852.fromSeed(seed, Cip1852Coins.cardanoIcarus);

  /// m/1852'/1815'/0'
  final deriveToAccount = cip1852.purpose.coin.account(0);

  /// m/1852'/1815'/0'/0/0
  final shelly = CardanoShelley.fromCip1852Object(deriveToAccount)
      .change(Bip44Changes.chainExt)
      .addressIndex(0);
  const yoroiAddr =
      "addr1qxflkflg370pzn3a3kvpwac4xv43as7req2h7ng95579w2rn0z556dsslncjzpeesuz3m63dwzj6mudd3ezxv4xtgmfscajp8k";
  final baseAddr = ADABaseAddress.fromPublicKey(
      basePubkeyBytes: shelly.bip44.publicKey.compressed,
      stakePubkeyBytes: shelly.bip44Sk.publicKey.compressed);
  assert(yoroiAddr == baseAddr.address);

```

**Comment by detherminal** [comment]
That also worked, thank you so much!
