### ISSUE TITLE
No `amount` in `ADATransactionOutput`

### ISSUE THREAD

**Issue by detherminal** [mrtnetwork/On_chain#9]
There isn't an `amount` property in `ADATransactionOutput` unlike [described in the Blockfrost docs](https://blockfrost.dev/api/transaction-utx-os).

**Comment by mrtnetwork** [comment]
> There isn't an `amount` property in `ADATransactionOutput` unlike [described in the Blockfrost docs](https://blockfrost.dev/api/transaction-utx-os).

Thank you for reporting that. The fix has been implemented in version 4.0.1.
